services:
  - type: web
    name: skillswap-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: skillswap-mongo
          property: connectionString
      - key: TIDB_CONNECTION_STRING
        value: your_tidb_cloud_connection_string_here

databases:
  - name: skillswap-mongo
    databaseName: skillswap_db
    user: skillswap_user
